In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\dell\anaconda3\lib\site-packages (4.16.0)
Requirement already satisfied: trio~=0.17 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (0.23.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: sortedcontainers in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: outcome in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: idna in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\dell\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

[QUESTION - 1].

Scrape  the  details  of  most  viewed  videos  on  YouTube  from  Wikipedia.  

Url  = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos 

You need to find following details:  

(A) Rank  
(B) Name   
(C) Artist   
(D) Upload date   
(E) Views

In [2]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import time
import requests as re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException

In [3]:
driver = webdriver.Chrome()

In [4]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [5]:
video_name=[]
name=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers col3center col4right jquery-tablesorter"][1]/tbody/tr/td[1]')
for i in name:
    video_name.append(i.text)

In [6]:
uploader_name=[]
name=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers col3center col4right jquery-tablesorter"][1]/tbody/tr/td[2]')
for i in name:
    uploader_name.append(i.text)

In [7]:
views_billions=[]
billions=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers col3center col4right jquery-tablesorter"][1]/tbody/tr/td[3]')
for i in billions:
    views_billions.append(i.text)

In [8]:
upload_date=[]
date=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers col3center col4right jquery-tablesorter"][1]/tbody/tr/td[4]')
for i in date:
    upload_date.append(i.text)

In [9]:
print(len(video_name),len(uploader_name),len(views_billions),len(upload_date))

30 30 30 30

In [10]:
df=pd.DataFrame({'Video': video_name, 'Uploader': uploader_name, 'Views(Billions)': views_billions, 'Upload Date': upload_date})
df

,Video,Uploader,Views(Billions),Upload Date
0,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - Kids' Songs & Stories,13.78,"June 17, 2016"
1,"""Despacito""[9]",Luis Fonsi,8.33,"January 12, 2017"
2,"""Johny Johny Yes Papa""[17]",LooLoo Kids - Nursery Rhymes and Children's Songs,6.85,"October 8, 2016"
3,"""Bath Song""[18]",Cocomelon - Nursery Rhymes,6.52,"May 2, 2018"
4,"""Shape of You""[19]",Ed Sheeran,6.15,"January 30, 2017"
5,"""See You Again""[22]",Wiz Khalifa,6.11,"April 6, 2015"
6,"""Wheels on the Bus""[27]",Cocomelon - Nursery Rhymes,5.74,"May 24, 2018"
7,"""Phonics Song with Two Words""[28]",ChuChu TV Nursery Rhymes & Kids Songs,5.59,"March 6, 2014"
8,"""Uptown Funk""[29]",Mark Ronson,5.10,"November 19, 2014"
9,"""Learning Colors – Colorful Eggs on a Farm""[30]",Miroshka TV,5.03,"February 27, 2018"
10,"""Gangnam Style""[31]",Psy,4.98,"July 15, 2012"
11,"""Masha and the Bear – Recipe for Disaster""[36]",Get Movies,4.57,"January 31, 2012"
12,"""Dame Tu Cosita""[37]",Ultra Records,4.49,"April 5, 2018"
13,"""Axel F""[38]",Crazy Frog,4.19,"June 16, 2009"
14,"""Sugar""[39]",Maroon 5,3.97,"January 14, 2015"
15,"""Counting Stars""[40]",OneRepublic,3.93,"May 31, 2013"
16,"""Roar""[41]",Katy Perry,3.92,"September 5, 2013"
17,"""Baa Baa Black Sheep""[42]",Cocomelon - Nursery Rhymes,3.86,"June 25, 2018"
18,"""Waka Waka (This Time for Africa)""[43]",Shakira,3.80,"June 4, 2010"
19,"""Lakdi Ki Kathi""[44]",Jingle Toons,3.78,"June 14, 2018"
20,"""Sorry""[45]",Justin Bieber,3.74,"October 22, 2015"
21,"""Thinking Out Loud""[46]",Ed Sheeran,3.70,"October 7, 2014"
22,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.65,"January 26, 2018"
23,"""Dark Horse""[48]",Katy Perry,3.64,"February 20, 2014"
24,"""Perfect""[49]",Ed Sheeran,3.61,"November 9, 2017"
25,"""Shree Hanuman Chalisa""[50]",T-Series Bhakti Sagar,3.57,"May 10, 2011"
26,"""Let Her Go""[51]",Passenger,3.57,"July 25, 2012"
27,"""Faded""[52]",Alan Walker,3.56,"December 3, 2015"
28,"""Girls Like You""[53]",Maroon 5,3.53,"May 31, 2018"
29,"""Lean On""[54]",Major Lazer Official,3.51,"March 22, 2015"

[QUESTION - 2]. 

Scrape the details team India’s international fixtures from bcci.tv.   

Url = https://www.bcci.tv/.   

You need to find following details:   

(A) Series   
(B) Place   
(C) Date   
(D) Time   

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [2]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import time
import requests as re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException

In [3]:
driver = webdriver.Chrome()

In [4]:
driver.get("https://www.bcci.tv/")

In [5]:
driver.find_element(By.XPATH,"//a[text()='Fixtures']").click()

In [6]:
series_tour=[]
tour=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
for i in tour:
    series_tour.append(i.text)

In [7]:
series_tour

['INDIA TOUR OF SOUTH AFRICA 2023-24',
 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24',
 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24',
 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24',
 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24',
 'AUSTRALIA WOMEN TOUR OF INDIA 2023-24',
 'AFGHANISTAN TOUR OF INDIA 2023-24']

In [8]:
match_date=[]
date=driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for i in date:
    match_date.append(i.text)

In [9]:
match_date

['26 DECEMBER, 2023',
 '28 DECEMBER, 2023',
 '30 DECEMBER, 2023',
 '2 JANUARY, 2024',
 '3 JANUARY, 2024',
 '5 JANUARY, 2024',
 '7 JANUARY, 2024',
 '9 JANUARY, 2024',
 '11 JANUARY, 2024']

In [10]:
series_name=[]
name=driver.find_elements(By.XPATH,'//div[@class="tags-wrap"]/span[1]')
for i in name:
    series_name.append(i.text)

In [11]:
series_name

['1st Test',
 '1st ODI',
 '2nd ODI',
 '3rd ODI',
 '2nd Test',
 '1st T20I',
 '2nd T20I',
 '3rd T20I',
 '1st T20I']

In [13]:
time_value=[]
value=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for i in value:
    time_value.append(i.text)

In [14]:
time_value

['1:30 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '1:30 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST']

In [15]:
place_name=[]
name=driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope"]')
for i in name:
    place_name.append(str(i.text).replace("\n",""))

In [16]:
place_name

['Wankhede Stadium, Mumbai',
 'Wankhede Stadium, Mumbai',
 'Wankhede Stadium, Mumbai',
 'Newlands, Cape Town',
 'DY Patil Stadium, NAVI MUMBAI',
 'DY Patil Stadium, NAVI MUMBAI',
 'DY Patil Stadium, NAVI MUMBAI',
 'Punjab Cricket Association IS Bindra Stadium, Mohali']

In [17]:
df=pd.DataFrame({'Tour': series_tour, 'Series Name': series_name, 'Date': match_date, 'Time': time_value})
df

,Tour,Series Name,Date,Time
0,INDIA TOUR OF SOUTH AFRICA 2023-24,1st Test,"26 DECEMBER, 2023",1:30 PM IST
1,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,1st ODI,"28 DECEMBER, 2023",2:00 PM IST
2,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,2nd ODI,"30 DECEMBER, 2023",2:00 PM IST
3,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,3rd ODI,"2 JANUARY, 2024",2:00 PM IST
4,INDIA TOUR OF SOUTH AFRICA 2023-24,2nd Test,"3 JANUARY, 2024",1:30 PM IST
5,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,1st T20I,"5 JANUARY, 2024",7:00 PM IST
6,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,2nd T20I,"7 JANUARY, 2024",7:00 PM IST
7,AUSTRALIA WOMEN TOUR OF INDIA 2023-24,3rd T20I,"9 JANUARY, 2024",7:00 PM IST
8,AFGHANISTAN TOUR OF INDIA 2023-24,1st T20I,"11 JANUARY, 2024",7:00 PM IST

[QUESTION - 3]. 

Scrape the details of State-wise GDP of India from statisticstime.com.   Url = http://statisticstimes.com/   

You have to find following details: 

(A) Rank   
(B) State   
(C) GSDP(18-19)- at current prices   
(D) GSDP(19-20)- at current prices   
(E) Share(18-19)   
(F) GDP($ billion)   

Note: - From statisticstimes home page you have to reach to economy page through code.

In [2]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import time
import requests as re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get("http://statisticstimes.com/")

In [7]:
driver.find_element(By.XPATH,'/html/body/div/div[1]/div[2]/div[2]/button').click()

In [8]:
driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]').click()

In [9]:
rank_numb=[]
numb=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
for i in numb:
    rank_numb.append(i.text)

In [10]:
state_name=[]
name=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
for i in name:
    state_name.append(i.text)

In [11]:
gsdp_prices=[]
prices=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
for i in prices:
    gsdp_prices.append(i.text)

In [12]:
gsdp_price=[]
price=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
for i in price:
    gsdp_price.append(i.text)

In [13]:
share_percent=[]
percent=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
for i in percent:
    share_percent.append(i.text)

In [14]:
gdp_billions=[]
billions=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
for i in billions:
    gdp_billions.append(i.text)

In [15]:
print(len(rank_numb),len(state_name),len(gdp_billions),len(gsdp_prices),len(gsdp_price),len(share_percent))

33 33 33 33 33 33

In [16]:
df=pd.DataFrame({'Rank': rank_numb, 'State': state_name, 'GSDP(22-23) Current Prices': gsdp_prices, 'GSDP(21-22) Current Prices': gsdp_price, 'Share': share_percent, 'GDP($Billion)': gdp_billions})
df

,Rank,State,GSDP(22-23) Current Prices,GSDP(21-22) Current Prices,Share,GDP($Billion)
0,1,Maharashtra,-,"3,108,022",13.24%,417.163
1,2,Tamil Nadu,"2,364,514","2,071,286",8.82%,278.011
2,3,Uttar Pradesh,"2,257,575","1,974,532",8.41%,265.024
3,4,Karnataka,"2,241,368","1,962,725",8.36%,263.440
4,5,Gujarat,-,"1,937,066",8.25%,259.996
5,6,West Bengal,"1,554,992","1,363,926",5.81%,183.068
6,7,Rajasthan,"1,413,620","1,218,193",5.19%,163.507
7,8,Madhya Pradesh,"1,322,821","1,136,137",4.84%,152.494
8,9,Andhra Pradesh,"1,317,728","1,133,837",4.83%,152.185
9,10,Telangana,"1,313,391","1,128,907",4.81%,151.523
10,11,Kerala,-,"932,470",3.97%,125.157
11,12,Delhi,"1,043,759","904,642",3.85%,121.422
12,13,Haryana,"994,154","870,665",3.71%,116.862
13,14,Odisha,"774,869","670,881",2.86%,90.047
14,15,Bihar,"751,396","650,302",2.77%,87.284
15,16,Punjab,"673,107","614,227",2.62%,82.442
16,17,Assam,"493,167","412,612",1.76%,55.381
17,18,Chhattisgarh,"457,608","406,416",1.73%,54.550
18,19,Jharkhand,"393,722","358,863",1.53%,48.167
19,20,Uttarakhand,"302,621","272,159",1.16%,36.530
20,21,Jammu & Kashmir-UT,"227,927","199,917",0.85%,26.833
21,22,Himachal Pradesh,"195,405","176,269",0.75%,23.659
22,23,Goa,-,"82,604",0.35%,11.087
23,24,Tripura,"72,636","62,550",0.27%,8.396
24,25,Chandigarh,-,"45,635",0.19%,6.125
25,26,Puducherry,-,"44,238",0.19%,5.938
26,27,Meghalaya,"42,697","38,785",0.17%,5.206
27,28,Sikkim,"42,756","37,557",0.16%,5.041
28,29,Manipur,-,"36,594",0.16%,4.912
29,30,Arunachal Pradesh,-,"35,124",0.15%,4.714
30,31,Nagaland,-,"31,913",0.14%,4.283
31,32,Mizoram,-,"27,824",0.12%,3.735
32,33,Andaman & Nicobar Islands,-,"10,371",0.04%,1.392

[QUESTION - 4]. 

Scrape the details of trending repositories on Github.com.   Url = https://github.com/   

You have to find the following details:   

(A) Repository title   
(B) Repository description   
(C) Contributors count   
(D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [2]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import time
import requests as re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException

In [3]:
driver = webdriver.Chrome()

In [4]:
driver.get("https://github.com/")

In [6]:
driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button').click()

In [7]:
driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a').click()

In [8]:
title_name=[]
name=driver.find_elements(By.XPATH,'//span[@class="text-normal"]')
for i in name:
    title_name.append(i.text)

In [9]:
description_notes=[]
notes=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for i in notes:
    description_notes.append(i.text)

In [10]:
contributors_count=[]
count=driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]/a[2]')
for i in count:
    contributors_count.append(i.text)

In [11]:
language_used=[]
used=driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]/span[1]')
for i in used:
    language_used.append(i.text)

In [12]:
print(len(title_name),len(description_notes),len(contributors_count),len(language_used))

25 25 25 25

In [13]:
df=pd.DataFrame({'Repository Title': title_name, 'Repository Description': description_notes, 'Contributors Count': contributors_count, 'Language used': language_used})
df

,Repository Title,Repository Description,Contributors Count,Language used
0,Frooodle /,locally hosted web application that allows you...,830,Java
1,BartoszJarocki /,"Print-friendly, minimalist CV page",284,TypeScript
2,nomic-ai /,gpt4all: open-source LLM chatbots that you can...,"6,475",C++
3,nodejs /,"An HTTP/1.1 client, written from scratch for N...",435,JavaScript
4,shadcn-ui /,Beautifully designed components that you can c...,"2,047",TypeScript
5,apache /,"Upserts, Deletes And Incremental Processing on...","2,430",Java
6,microsoft /,A unified evaluation framework for large langu...,99,Python
7,Hillobar /,GUI-focused roop,241,Python
8,karanpratapsingh /,Learn how to design systems at scale and prepa...,"2,405",Built by
9,DopplerHQ /,A curated awesome list of lists of interview q...,"8,052",Built by
10,movie-web /,A small web app for watching movies and shows ...,510,TypeScript
11,HuolalaTech /,Debug remotely and easily like chrome devtools.,217,TypeScript
12,THUDM /,ChatGLM3 series: Open Bilingual Chat LLMs | 开源...,832,Python
13,d3george /,"A modern react admin. It is based on react 18,...",61,TypeScript
14,iusztinpaul /,"🦖 𝗟𝗲𝗮𝗿𝗻 about 𝗟𝗟𝗠𝘀, 𝗟𝗟𝗠𝗢𝗽𝘀, and 𝘃𝗲𝗰𝘁𝗼𝗿 𝗗𝗕𝘀 for...",176,Jupyter Notebook
15,cumulo-autumn /,StreamDiffusion: A Pipeline-Level Solution for...,386,Python
16,xinghaochen /,"Official PyTorch implementation of ""TinySAM: P...",12,Python
17,Flipper-XFW /,The Dom amongst the Flipper Zero Firmware. Giv...,503,C
18,unocss /,The instant on-demand atomic CSS engine.,709,TypeScript
19,alibaba-damo-academy /,A Fundamental End-to-End Speech Recognition To...,241,Python
20,mouredev /,Ruta de estudio basada en ejercicios de código...,195,Python
21,ant-design /,🥳 A React components collection for Web3!,42,TypeScript
22,jqnatividad /,"CSVs sliced, diced & analyzed.",53,Rust
23,nuxt /,The Intuitive Vue Framework.,"4,643",TypeScript
24,baaivision /,Emu Series: Generative Multimodal Models from ...,64,Python

[QUESTION - 5]. 

Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/  

You have to find the following details:   

(A) Song name   
(B) Artist name   
(C) Last week rank   
(D) Peak rank   
(E) Weeks on board   
 
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [2]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import time
import requests as re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get("https:/www.billboard.com/")

In [5]:
driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]').click()

In [6]:
driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]').click()

In [7]:
song_name=[]
name=driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/h3')
for i in name:
    song_name.append(i.text)

In [8]:
song_name

['All I Want For Christmas Is You',
 "Rockin' Around The Christmas Tree",
 'Jingle Bell Rock',
 'Last Christmas',
 'A Holly Jolly Christmas',
 'Lovin On Me',
 "It's The Most Wonderful Time Of The Year",
 'Let It Snow, Let It Snow, Let It Snow!',
 'Feliz Navidad',
 'Sleigh Ride',
 'The Christmas Song (Merry Christmas To You)',
 'Santa Tell Me',
 'Underneath The Tree',
 "It's Beginning To Look A Lot Like Christmas",
 'White Christmas',
 'Jingle Bells',
 'Christmas (Baby Please Come Home)',
 'Cruel Summer',
 'Greedy',
 'Snooze',
 'Paint The Town Red',
 'Here Comes Santa Claus (Right Down Santa Claus Lane)',
 'Deck The Halls',
 "It's Beginning To Look A Lot Like Christmas",
 'Blue Christmas',
 'Water',
 'Run Rudolph Run',
 'I Remember Everything',
 'Agora Hills',
 'Santa Baby',
 'Little Saint Nick',
 'Please Come Home For Christmas',
 'Last Night',
 "You're A Mean One, Mr. Grinch",
 "Santa Claus Is Comin' To Town",
 'Wonderful Christmastime',
 "Thinkin' Bout Me",
 'Rudolph The Red-Nosed Reindeer',
 'Everybody',
 "Is It Over Now? (Taylor's Version) [From The Vault]",
 'Lose Control',
 'FTCU',
 "Like It's Christmas",
 'Happy Holiday / The Holiday Season',
 'This Christmas',
 'Fast Car',
 'Lil Boo Thang',
 'Happy Xmas (War Is Over)',
 'What Was I Made For?',
 'Rich Baby Daddy',
 'First Person Shooter',
 'White Horse',
 'Stick Season',
 'Used To Be Young',
 'World On Fire',
 'Good Good',
 'Houdini',
 'My Love Mine All Mine',
 'Pretty Little Poison',
 'Exes',
 'Surround Sound',
 'On My Mama',
 'IDGAF',
 'Monaco',
 'Needle',
 'Strangers',
 'Wild Ones',
 'Get Him Back!',
 'Harley Quinn',
 'You Broke My Heart',
 'Bellakeo',
 'Truck Bed',
 'Save Me The Trouble',
 'Beep Beep',
 '500lbs',
 'La Diabla',
 "You're Losing Me (From The Vault)",
 'Where The Wild Things Are',
 'Standing Next To You',
 'The Painter',
 'Jingle Bells',
 'Qlona',
 'Crazy',
 'Never Lose Me',
 'Lace It',
 'Burn It Down',
 "Can't Catch Me Now",
 'Mind On You',
 'Segun Quien',
 'Feather',
 'La Victima',
 'Hey Driver',
 'Wondering Why',
 'DJ Play A Christmas Song',
 "Different 'Round Here",
 'Winter Wonderland',
 'Run For The Hills',
 'Que Onda',
 'Great Gatsby',
 'One Of The Girls']

In [9]:
song_rank=[]
rank=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"][1]')
for i in rank:
    song_rank.append(i.text)

In [10]:
song_rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '10',
 '12',
 '8',
 '15',
 '14',
 '11',
 '24',
 '23',
 '20',
 '18',
 '13',
 '9',
 '16',
 '17',
 '25',
 '28',
 '19',
 '27',
 '21',
 '38',
 '22',
 '30',
 '31',
 '40',
 '45',
 '29',
 '41',
 '37',
 '35',
 '32',
 '33',
 '26',
 '36',
 '47',
 '42',
 '46',
 '49',
 '-',
 '39',
 '43',
 '-',
 '53',
 '44',
 '51',
 '55',
 '54',
 '52',
 '62',
 '56',
 '59',
 '61',
 '71',
 '57',
 '72',
 '70',
 '66',
 '67',
 '34',
 '78',
 '77',
 '79',
 '76',
 '83',
 '-',
 '85',
 '96',
 '64',
 '81',
 '-',
 '68',
 '90',
 '99',
 '88',
 '-',
 '86',
 '-',
 '-',
 '-',
 '93',
 '84',
 '-',
 '91',
 '94',
 '-',
 '97',
 '-',
 '-',
 '-',
 '-',
 '69',
 '92',
 '-',
 '-']

In [11]:
peak_rank=[]
rank=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max"][2]')
for i in rank:
    peak_rank.append(i.text)

In [12]:
peak_rank

['1',
 '1',
 '3',
 '4',
 '4',
 '1',
 '5',
 '8',
 '6',
 '8',
 '9',
 '12',
 '11',
 '12',
 '12',
 '16',
 '15',
 '1',
 '7',
 '2',
 '1',
 '22',
 '16',
 '19',
 '24',
 '10',
 '10',
 '1',
 '14',
 '30',
 '29',
 '18',
 '1',
 '31',
 '33',
 '28',
 '7',
 '16',
 '26',
 '1',
 '39',
 '42',
 '43',
 '18',
 '37',
 '2',
 '23',
 '38',
 '14',
 '11',
 '1',
 '12',
 '31',
 '8',
 '47',
 '25',
 '11',
 '26',
 '46',
 '34',
 '61',
 '48',
 '2',
 '5',
 '34',
 '52',
 '42',
 '11',
 '40',
 '11',
 '71',
 '55',
 '73',
 '64',
 '51',
 '76',
 '27',
 '78',
 '5',
 '55',
 '81',
 '28',
 '83',
 '84',
 '85',
 '77',
 '56',
 '88',
 '68',
 '90',
 '91',
 '14',
 '93',
 '94',
 '95',
 '96',
 '69',
 '61',
 '30',
 '100']

In [13]:
wks_on_chart=[]
chart=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"][2]')
for i in chart:
    wks_on_chart.append(i.text)

In [14]:
wks_on_chart

['64',
 '57',
 '55',
 '37',
 '38',
 '6',
 '38',
 '30',
 '31',
 '27',
 '43',
 '23',
 '26',
 '22',
 '34',
 '13',
 '21',
 '33',
 '14',
 '54',
 '20',
 '19',
 '12',
 '19',
 '12',
 '12',
 '21',
 '17',
 '13',
 '8',
 '7',
 '14',
 '47',
 '11',
 '10',
 '12',
 '42',
 '26',
 '2',
 '8',
 '19',
 '2',
 '6',
 '18',
 '4',
 '39',
 '14',
 '5',
 '23',
 '11',
 '11',
 '22',
 '12',
 '17',
 '8',
 '19',
 '6',
 '13',
 '15',
 '5',
 '6',
 '14',
 '11',
 '10',
 '2',
 '14',
 '11',
 '15',
 '7',
 '5',
 '1',
 '27',
 '8',
 '2',
 '13',
 '1',
 '4',
 '5',
 '7',
 '11',
 '1',
 '19',
 '1',
 '1',
 '1',
 '9',
 '7',
 '1',
 '12',
 '3',
 '1',
 '17',
 '1',
 '1',
 '4',
 '1',
 '2',
 '12',
 '13',
 '1']

In [15]:
artist_name=[]
name=driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
for i in name:
    artist_name.append(i.text)

In [16]:
artist_name

['Brenda Lee',
 'Bobby Helms',
 'Wham!',
 'Burl Ives',
 'Jack Harlow',
 'Andy Williams',
 'Dean Martin',
 'Jose Feliciano',
 'The Ronettes',
 'Nat King Cole',
 'Ariana Grande',
 'Kelly Clarkson',
 'Perry Como And The Fontane Sisters With Mitchell Ayres And His Orchestra',
 'Bing Crosby With Ken Darby Singers & John Scott Trotter & His Orchestra',
 'Frank Sinatra With Orchestra Conducted By Gordon Jenkins',
 'Darlene Love',
 'Taylor Swift',
 'Tate McRae',
 'SZA',
 'Doja Cat',
 'Gene Autry',
 'Nat King Cole',
 'Michael Buble',
 'Elvis Presley',
 'Tyla',
 'Chuck Berry',
 'Zach Bryan Featuring Kacey Musgraves',
 'Doja Cat',
 'Eartha Kitt With Henri Rene And His Orchestra',
 'The Beach Boys',
 'Eagles',
 'Morgan Wallen',
 'Thurl Ravenscroft',
 'Jackson 5',
 'Paul McCartney',
 'Morgan Wallen',
 'Gene Autry & The Pinafores',
 'Nicki Minaj Featuring Lil Uzi Vert',
 'Taylor Swift',
 'Teddy Swims',
 'Nicki Minaj',
 'Jonas Brothers',
 'Andy Williams',
 'Donny Hathaway',
 'Luke Combs',
 'Paul Russell',
 'John & Yoko/The Plastic Ono Band With The Harlem Community Choir',
 'Billie Eilish',
 'Drake Featuring Sexyy Red & SZA',
 'Drake Featuring J. Cole',
 'Chris Stapleton',
 'Noah Kahan',
 'Miley Cyrus',
 'Nate Smith',
 'Usher, Summer Walker & 21 Savage',
 'Dua Lipa',
 'Mitski',
 'Warren Zeiders',
 'Tate McRae',
 'JID Featuring 21 Savage & Baby Tate',
 'Victoria Monet',
 'Drake Featuring Yeat',
 'Bad Bunny',
 'Nicki Minaj Featuring Drake',
 'Kenya Grace',
 'Jessie Murph & Jelly Roll',
 'Olivia Rodrigo',
 'Fuerza Regida & Marshmello',
 'Drake',
 'Peso Pluma & Anitta',
 'HARDY',
 'Dan + Shay',
 'Nicki Minaj',
 'Lil Tecca',
 'Xavi',
 'Taylor Swift',
 'Luke Combs',
 'Jung Kook',
 'Cody Johnson',
 'Meghan Trainor',
 'Karol G & Peso Pluma',
 'Lil Baby',
 'Flo Milli',
 'Juice WRLD, Eminem & benny blanco',
 'Parker McCollum',
 'Olivia Rodrigo',
 'George Birge',
 'Maluma & Carin Leon',
 'Sabrina Carpenter',
 'Xavi',
 'Zach Bryan Featuring The War And Treaty',
 'The Red Clay Strays',
 'Cher',
 'Riley Green Featuring Luke Combs',
 'Chloe',
 'Tate McRae',
 'Calle 24 x Chino Pacas x Fuerza Regida',
 'Rod Wave',
 'The Weeknd, JENNIE & Lily Rose Depp']

In [17]:
df=pd.DataFrame({'Song': song_name, 'Last Week Rank': song_rank, 'Peak Rank': peak_rank, 'Week On Chart': wks_on_chart})
df

                                 Song Last Week Rank Peak Rank Week On Chart
0     All I Want For Christmas Is You              1         1            64
1   Rockin' Around The Christmas Tree              2         1            57
2                    Jingle Bell Rock              3         3            55
3                      Last Christmas              4         4            37
4             A Holly Jolly Christmas              5         4            38
..                                ...            ...       ...           ...
95                  Winter Wonderland              -        96             1
96                  Run For The Hills             69        69             2
97                           Que Onda             92        61            12
98                       Great Gatsby              -        30            13
99                   One Of The Girls              -       100             1

[100 rows x 4 columns]

[QUESTION - 6]. 

Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare   

Scrape the details of Highest selling novels.   

(A) Book name   
(B) Author name   
(C) Volumes sold   
(D) Publisher   
(E) Genre

In [26]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import time
import requests as re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException

In [27]:
driver=webdriver.Chrome()

In [28]:
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [29]:
title_name=[]
name=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
for i in name:
    title_name.append(i.text)

In [31]:
author_name=[]
name=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
for i in name:
    author_name.append(i.text)

In [32]:
volume_sold=[]
sold=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
for i in sold:
    volume_sold.append(i.text)

In [33]:
publisher_name=[]
name=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
for i in name:
    publisher_name.append(i.text)

In [34]:
genre_name=[]
name=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
for i in name:
    genre_name.append(i.text)

In [35]:
print(len(title_name),len(author_name),len(volume_sold),len(publisher_name),len(genre_name))

100 100 100 100 100

In [36]:
df=pd.DataFrame({'Book Name': title_name, 'Author': author_name, 'Publisher': publisher_name, 'Volume Sold': volume_sold, 'Gemre': genre_name})
df

,Book Name,Author,Publisher,Volume Sold,Gemre
0,"Da Vinci Code,The","Brown, Dan",Transworld,"5,094,805","Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.",Bloomsbury,"4,475,152",Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",Bloomsbury,"4,200,654",Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",Bloomsbury,"4,179,479",Children's Fiction
4,Fifty Shades of Grey,"James, E. L.",Random House,"3,758,936",Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert",Random House,"807,311",General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie",Penguin,"794,201",Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne",Scholastic Ltd.,"792,187",Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave",Orion,"791,507",Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",Penguin,"791,095",Food & Drink: General

[QUESTION - 7]. 

Scrape the details most watched tv series of all time from imdb.com.   

Url = https://www.imdb.com/list/ls095964455/ 

You have to find the following details:

(A) Name   
(B) Year span   
(C) Genre   
(D) Run time   
(E) Ratings   
(F) Votes

In [2]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import time
import requests as re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get("https://www.imdb.com/list/ls095964455/")

The requested URL was not found on server.

I Solve most popular TV Shows from imbd.com -

In [5]:
driver.get("https://www.imdb.com/chart/tvmeter/?ref_=nv_tvv_mptv")

In [6]:
shows_name=[]
name=driver.find_elements(By.XPATH,'//div[@class="ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-43986a27-9 gaoUku cli-title"]/a/h3')
for i in name:
    shows_name.append(i.text)

In [7]:
shows_year=[]
year=driver.find_elements(By.XPATH,'//div[@class="sc-43986a27-7 dBkaPT cli-title-metadata"]/span[1]')
for i in year:
    shows_year.append(i.text)

In [8]:
episode_count=[]
count=driver.find_elements(By.XPATH,'//div[@class="sc-43986a27-7 dBkaPT cli-title-metadata"]/span[2]')
for i in count:
    episode_count.append(i.text)

In [9]:
tv_group=[]
group=driver.find_elements(By.XPATH,'//div[@class="sc-43986a27-7 dBkaPT cli-title-metadata"]/span[3]')
for i in group:
    tv_group.append(i.text)

In [10]:
vote_number=[]
number=driver.find_elements(By.XPATH,'//span[@class="ipc-rating-star--voteCount"]')
for i in number:
    vote_number.append(i.text)

In [13]:
(shows_name,shows_year,episode_count,tv_group,vote_number)

(['Reacher',
  'Percy Jackson and the Olympians',
  'The Crown',
  'Fargo',
  'Doctor Who',
  'Rick and Morty',
  'Obliterated',
  'My Life with the Walter Boys',
  'Slow Horses',
  'Monarch: Legacy of Monsters',
  'The Gilded Age',
  'A Murder at the End of the World',
  'Game of Thrones',
  'Yu Yu Hakusho',
  'Jujutsu Kaisen',
  'The Boys',
  'Vigil',
  'True Detective',
  'Blue Eye Samurai',
  'For All Mankind',
  'Yellowstone',
  'Suits',
  'Lawmen: Bass Reeves',
  "Grey's Anatomy",
  'Breaking Bad',
  'Young Sheldon',
  'Dr. Death',
  'The Walking Dead',
  'The Bear',
  'Friends',
  'Yellowjackets',
  'The Fall of the House of Usher',
  'Archie',
  'The Santa Clauses',
  'The Office',
  'The Sopranos',
  'Shameless',
  'Attack on Titan',
  'Invincible',
  'What If...?',
  'The Rookie',
  'Supernatural',
  'Stranger Things',
  'The Double Life of My Billionaire Husband',
  'Black Mirror',
  'Ted Lasso',
  'Fellow Travelers',
  'Succession',
  'The Big Bang Theory',
  'Criminal Minds',
  'One Piece',
  'Peaky Blinders',
  'School Spirits',
  'The Last of Us',
  'House of the Dragon',
  'Carol & The End of the World',
  'South Park',
  'Lessons in Chemistry',
  'American Horror Story',
  'Midsomer Murders',
  'Law & Order: Special Victims Unit',
  'Fallout',
  'Bodies',
  'Bookie',
  'NCIS',
  'Sex Education',
  'Archer',
  'The Curse',
  'All the Light We Cannot See',
  'Vikings',
  'Better Call Saul',
  'Modern Family',
  'Gen V',
  'House',
  'Loki',
  'Band of Brothers',
  'Shetland',
  'The Artful Dodger',
  'Brooklyn Nine-Nine',
  'Sweet Home',
  'The Night Agent',
  "It's Always Sunny in Philadelphia",
  'Silo',
  'The Wire',
  'Euphoria',
  'The Witcher',
  'The Morning Show',
  'Julia',
  'A Nearly Normal Family',
  'The X-Files',
  'Seinfeld',
  'The White Lotus',
  'From',
  'Beacon 23',
  'Bones',
  'Family Guy',
  'One Piece',
  'Halo',
  'Six Feet Under',
  'Only Murders in the Building'],
 ['2022–',
  '2023–',
  '2016–2023',
  '2014–2024',
  '2005–',
  '2013–',
  '2023',
  '2023–',
  '2022–',
  '2023–',
  '2022–',
  '2023',
  '2011–2019',
  '2023–',
  '2020–',
  '2019–',
  '2021–',
  '2014–',
  '2023',
  '2019–',
  '2018–',
  '2011–2019',
  '2023',
  '2005–',
  '2008–2013',
  '2017–2024',
  '2021–2023',
  '2010–2022',
  '2022–',
  '1994–2004',
  '2021–',
  '2023',
  '2023',
  '2022–2023',
  '2005–2013',
  '1999–2007',
  '2011–2021',
  '2013–2023',
  '2021–',
  '2021–',
  '2018–',
  '2005–2020',
  '2016–2025',
  '2023–',
  '2011–',
  '2020–2023',
  '2023',
  '2018–2023',
  '2007–2019',
  '2005–',
  '1999–',
  '2013–2022',
  '2023–',
  '2023–',
  '2022–',
  '2023',
  '1997–',
  '2023',
  '2011–',
  '1997–',
  '1999–',
  '2024–',
  '2023',
  '2023–',
  '2003–',
  '2019–2023',
  '2009–2023',
  '2023–',
  '2023',
  '2013–2020',
  '2015–2022',
  '2009–2020',
  '2023–',
  '2004–2012',
  '2021–2023',
  '2001',
  '2013–',
  '2023–',
  '2013–2021',
  '2020–',
  '2023–',
  '2005–',
  '2023–',
  '2002–2008',
  '2019–',
  '2019–',
  '2019–',
  '2022–',
  '2023',
  '1993–2018',
  '1989–1998',
  '2021–2025',
  '2022–',
  '2023–',
  '2005–2017',
  '1999–',
  '2023–',
  '2022–',
  '2001–2005',
  '2021–'],
 ['17 eps',
  '8 eps',
  '60 eps',
  '51 eps',
  '196 eps',
  '74 eps',
  '8 eps',
  '10 eps',
  '24 eps',
  '10 eps',
  '18 eps',
  '7 eps',
  '73 eps',
  '5 eps',
  '47 eps',
  '32 eps',
  '12 eps',
  '30 eps',
  '9 eps',
  '40 eps',
  '53 eps',
  '134 eps',
  '8 eps',
  '421 eps',
  '62 eps',
  '141 eps',
  '16 eps',
  '177 eps',
  '19 eps',
  '234 eps',
  '20 eps',
  '8 eps',
  '4 eps',
  '12 eps',
  '188 eps',
  '86 eps',
  '134 eps',
  '98 eps',
  '17 eps',
  '19 eps',
  '100 eps',
  '327 eps',
  '42 eps',
  '28 eps',
  '34 eps',
  '8 eps',
  '39 eps',
  '280 eps',
  '335 eps',
  '1097 eps',
  '36 eps',
  '9 eps',
  '10 eps',
  '20 eps',
  '10 eps',
  '330 eps',
  '8 eps',
  '129 eps',
  '140 eps',
  '540 eps',
  '8 eps',
  '8 eps',
  '8 eps',
  '458 eps',
  '32 eps',
  '144 eps',
  '10 eps',
  '4 eps',
  '93 eps',
  '63 eps',
  '250 eps',
  '10 eps',
  '176 eps',
  '12 eps',
  '10 eps',
  '44 eps',
  '8 eps',
  '153 eps',
  '19 eps',
  '11 eps',
  '172 eps',
  '20 eps',
  '60 eps',
  '19 eps',
  '25 eps',
  '31 eps',
  '16 eps',
  '6 eps',
  '217 eps',
  '173 eps',
  '14 eps',
  '30 eps',
  '17 eps',
  '245 eps',
  '420 eps',
  '9 eps',
  '17 eps',
  '63 eps',
  '40 eps'],
 ['TV-MA',
  'TV-PG',
  'TV-MA',
  'TV-MA',
  'TV-PG',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-MA',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-MA',
  'TV-14',
  'TV-MA',
  'TV-PG',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-PG',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-14',
  'TV-14',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-PG',
  'TV-14',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-PG',
  'TV-MA',
  'TV-14',
  'TV-14',
  'TV-MA',
  'TV-14',
  'TV-14',
  'TV-14',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-PG',
  'TV-MA',
  'TV-MA',
  'TV-MA',
  'TV-14',
  'TV-MA',
  'TV-14',
  'TV-14',
  'TV-MA',
  'TV-MA'],
 [' (167K)',
  ' (7.4K)',
  ' (245K)',
  ' (400K)',
  ' (242K)',
  ' (584K)',
  ' (11K)',
  ' (5.4K)',
  ' (54K)',
  ' (15K)',
  ' (34K)',
  ' (13K)',
  ' (2.2M)',
  ' (4.9K)',
  ' (99K)',
  ' (615K)',
  ' (25K)',
  ' (619K)',
  ' (38K)',
  ' (60K)',
  ' (200K)',
  ' (463K)',
  ' (6.4K)',
  ' (334K)',
  ' (2.1M)',
  ' (89K)',
  ' (15K)',
  ' (1.1M)',
  ' (173K)',
  ' (1.1M)',
  ' (79K)',
  ' (90K)',
  ' (1.4K)',
  ' (11K)',
  ' (684K)',
  ' (452K)',
  ' (272K)',
  ' (482K)',
  ' (184K)',
  ' (135K)',
  ' (61K)',
  ' (474K)',
  ' (1.3M)',
  ' (885)',
  ' (624K)',
  ' (325K)',
  ' (5.7K)',
  ' (249K)',
  ' (852K)',
  ' (214K)',
  ' (214K)',
  ' (623K)',
  ' (7.4K)',
  ' (479K)',
  ' (352K)',
  ' (1.4K)',
  ' (400K)',
  ' (21K)',
  ' (339K)',
  ' (38K)',
  ' (120K)',
  ' (41K)',
  ' (1.9K)',
  ' (159K)',
  ' (340K)',
  ' (164K)',
  ' (3.2K)',
  ' (34K)',
  ' (569K)',
  ' (622K)',
  ' (470K)',
  ' (70K)',
  ' (498K)',
  ' (398K)',
  ' (510K)',
  ' (24K)',
  ' (3K)',
  ' (350K)',
  ' (30K)',
  ' (100K)',
  ' (246K)',
  ' (102K)',
  ' (368K)',
  ' (226K)',
  ' (559K)',
  ' (124K)',
  ' (12K)',
  ' (8.5K)',
  ' (244K)',
  ' (344K)',
  ' (191K)',
  ' (61K)',
  ' (2.2K)',
  ' (173K)',
  ' (359K)',
  ' (131K)',
  ' (72K)',
  ' (146K)',
  ' (147K)'])

[QUESTION - 8]. 

Details of Datasets from UCI machine learning repositories.   Url = https://archive.ics.uci.edu/  

You have to find the following details:   

(A) Dataset name   
(B) Data type   
(C) Task   
(D) Attribute type   
(E) No of instances   
(F) No of attribute 
(G) Year   
 
Note: - from the home page you have to go to the Show All Dataset page through code.

In [2]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
import time
import requests as re
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementClickInterceptedException

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get("https://archive.ics.uci.edu/")

In [5]:
driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]').click()

In [6]:
data_name=[]
name=driver.find_elements(By.XPATH,'//h2[@class="truncate text-primary"]')
for i in name:
    data_name.append(i.text)

In [7]:
data_types=[]
types=driver.find_elements(By.XPATH,'//p[@class="truncate"]')
for i in types:
    data_types.append(i.text)

In [8]:
task_types=[]
types=driver.find_elements(By.XPATH,'//div[@class="col-span-3 flex items-center gap-2"][2]')
for i in types:
    task_types.append(i.text)

In [9]:
attribute_types=[]
types=driver.find_elements(By.XPATH,'//table[@class="col-span-full my-2 table sm:col-start-2"]/tbody/tr/td[2]')
for i in types:
    attribute_types.append(i.text)

In [10]:
instances_numb=[]
numb=driver.find_elements(By.XPATH,'//div[@class="col-span-3 flex items-center gap-2"][3]')
for i in numb:
    instances_numb.append(i.text)

In [11]:
attribute_numb=[]
numb=driver.find_elements(By.XPATH,'//div[@class="col-span-3 flex items-center gap-2"][4]')
for i in numb:
    attribute_numb.append(i.text)

In [12]:
year_count=[]
count=driver.find_elements(By.XPATH,'//table[@class="col-span-full my-2 table sm:col-start-2"]/tbody/tr/td[3]')
for i in count:
    year_count.append(i.text)

In [13]:
print(len(data_name),len(data_types),len(task_types),len(attribute_types),len(instances_numb),len(attribute_numb),len(year_count))

10 10 10 10 10 10 10

In [14]:
df=pd.DataFrame({'Dataset Name': data_name, 'Data Type': data_types, 'Task': task_types, 'Attribute Type': attribute_types, 'No of instances': instances_numb, 'No of attribute': attribute_numb, 'Year': year_count})
df

,Dataset Name,Data Type,Task,Attribute Type,No of instances,No of attribute,Year
0,Iris,"A small classic dataset from Fisher, 1936. One...",Tabular,Real,150 Instances,4 Features,7/1/1988
1,Dry Bean Dataset,"Images of 13,611 grains of 7 different registe...",Multivariate,"Integer, Real",13.61K Instances,16 Features,9/14/2020
2,Rice (Cammeo and Osmancik),A total of 3810 rice grain's images were taken...,Multivariate,Real,3.81K Instances,7 Features,10/6/2019
3,Heart Disease,"4 databases: Cleveland, Hungary, Switzerland, ...",Multivariate,"Categorical, Integer, Real",303 Instances,13 Features,7/1/1988
4,Adult,Predict whether income exceeds $50K/yr based o...,Multivariate,"Categorical, Integer",48.84K Instances,14 Features,5/1/1996
5,Wine,Using chemical analysis to determine the origi...,Tabular,"Integer, Real",178 Instances,13 Features,7/1/1991
6,Breast Cancer Wisconsin (Diagnostic),Diagnostic Wisconsin Breast Cancer Database.,Multivariate,Real,569 Instances,30 Features,11/1/1995
7,Diabetes,This diabetes dataset is from AIM '94,"Multivariate, Time-Series","Categorical, Integer",1 Instances,20 Features,N/A
8,Wine Quality,"Two datasets are included, related to red and ...",Multivariate,Real,4.9K Instances,12 Features,10/7/2009
9,Car Evaluation,Derived from simple hierarchical decision mode...,Multivariate,Categorical,1.73K Instances,6 Features,6/1/1997